#makefile

all: goodbytes

goodbytes: Alarm.cpp Asset.cpp Camera.cpp ElectricalSystem.cpp Entry.cpp Fence.cpp Inventory.cpp main.cpp ParkSection.cpp Car.cpp MD5.cpp
	g++ -o goodbytes Alarm.cpp Asset.cpp Camera.cpp ElectricalSystem.cpp Entry.cpp Fence.cpp Inventory.cpp main.cpp ParkSection.cpp Car.cpp MD5.cpp

clean:
	rm goodbytes
	rm sessionlog.txt
